"""empty message

Revision ID: 13a426c8aeb3
Revises: c637eb2e0ec7
Create Date: 2020-04-06 14:01:12.258320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13a426c8aeb3'
down_revision = 'c637eb2e0ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('age_limit', sa.String(length=10), nullable=True))
    op.add_column('cars', sa.Column('car_acc', sa.String(length=100), nullable=True))
    op.add_column('cars', sa.Column('car_code', sa.String(length=10), nullable=True))
    op.add_column('cars', sa.Column('car_year', sa.String(length=5), nullable=True))
    op.add_column('cars', sa.Column('company', sa.String(length=30), nullable=True))
    op.add_column('cars', sa.Column('con_noncover', sa.Boolean(), nullable=True))
    op.add_column('cars', sa.Column('cov_car', sa.String(length=20), nullable=True))
    op.add_column('cars', sa.Column('cov_mandatory', sa.Boolean(), nullable=True))
    op.add_column('cars', sa.Column('cov_object', sa.String(length=5), nullable=True))
    op.add_column('cars', sa.Column('cov_person', sa.Boolean(), nullable=True))
    op.add_column('cars', sa.Column('cov_self', sa.String(length=20), nullable=True))
    op.add_column('cars', sa.Column('curtomer_name', sa.String(length=50), nullable=True))
    op.add_column('cars', sa.Column('customer_eq', sa.Boolean(), nullable=True))
    op.add_column('cars', sa.Column('customer_job', sa.String(length=50), nullable=True))
    op.add_column('cars', sa.Column('driver_id', sa.String(length=20), nullable=True))
    op.add_column('cars', sa.Column('driver_limit', sa.String(length=10), nullable=True))
    op.add_column('cars', sa.Column('driver_name', sa.String(length=50), nullable=True))
    op.add_column('cars', sa.Column('owner_address', sa.String(length=120), nullable=True))
    op.add_column('cars', sa.Column('owner_id', sa.String(length=20), nullable=True))
    op.add_column('cars', sa.Column('owner_job', sa.String(length=50), nullable=True))
    op.add_column('cars', sa.Column('owner_name', sa.String(length=50), nullable=True))
    op.add_column('cars', sa.Column('owner_telno', sa.String(length=15), nullable=True))
    op.add_column('cars', sa.Column('spc_blackbox', sa.Boolean(), nullable=True))
    op.add_column('cars', sa.Column('spc_emergency', sa.String(length=10), nullable=True))
    op.add_column('cars', sa.Column('spc_mileage', sa.Boolean(), nullable=True))
    op.drop_column('cars', 'customer_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('customer_name', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('cars', 'spc_mileage')
    op.drop_column('cars', 'spc_emergency')
    op.drop_column('cars', 'spc_blackbox')
    op.drop_column('cars', 'owner_telno')
    op.drop_column('cars', 'owner_name')
    op.drop_column('cars', 'owner_job')
    op.drop_column('cars', 'owner_id')
    op.drop_column('cars', 'owner_address')
    op.drop_column('cars', 'driver_name')
    op.drop_column('cars', 'driver_limit')
    op.drop_column('cars', 'driver_id')
    op.drop_column('cars', 'customer_job')
    op.drop_column('cars', 'customer_eq')
    op.drop_column('cars', 'curtomer_name')
    op.drop_column('cars', 'cov_self')
    op.drop_column('cars', 'cov_person')
    op.drop_column('cars', 'cov_object')
    op.drop_column('cars', 'cov_mandatory')
    op.drop_column('cars', 'cov_car')
    op.drop_column('cars', 'con_noncover')
    op.drop_column('cars', 'company')
    op.drop_column('cars', 'car_year')
    op.drop_column('cars', 'car_code')
    op.drop_column('cars', 'car_acc')
    op.drop_column('cars', 'age_limit')
    # ### end Alembic commands ###
