"""empty message

Revision ID: 31dd379a52b4
Revises: 13a426c8aeb3
Create Date: 2020-04-06 17:06:43.092051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31dd379a52b4'
down_revision = '13a426c8aeb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('customer_name', sa.String(length=50), nullable=True))
    op.drop_column('cars', 'curtomer_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('curtomer_name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('cars', 'customer_name')
    # ### end Alembic commands ###
