"""empty message

Revision ID: 323b55118128
Revises: 
Create Date: 2020-04-22 14:30:16.499005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323b55118128'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fc_id', sa.String(length=20), nullable=True),
    sa.Column('company', sa.String(length=30), nullable=True),
    sa.Column('customer_name', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.String(length=20), nullable=True),
    sa.Column('customer_address', sa.String(length=120), nullable=True),
    sa.Column('customer_telno', sa.String(length=15), nullable=True),
    sa.Column('customer_job', sa.String(length=50), nullable=True),
    sa.Column('customer_eq', sa.Boolean(), nullable=True),
    sa.Column('owner_name', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.String(length=20), nullable=True),
    sa.Column('owner_address', sa.String(length=120), nullable=True),
    sa.Column('owner_telno', sa.String(length=15), nullable=True),
    sa.Column('owner_job', sa.String(length=50), nullable=True),
    sa.Column('car_no', sa.String(length=20), nullable=True),
    sa.Column('car_name', sa.String(length=50), nullable=True),
    sa.Column('car_code', sa.String(length=10), nullable=True),
    sa.Column('car_year', sa.String(length=5), nullable=True),
    sa.Column('car_acc', sa.String(length=100), nullable=True),
    sa.Column('age_limit', sa.String(length=10), nullable=True),
    sa.Column('driver_limit', sa.String(length=10), nullable=True),
    sa.Column('driver_name', sa.String(length=50), nullable=True),
    sa.Column('driver_id', sa.String(length=20), nullable=True),
    sa.Column('cov_mandatory', sa.Boolean(), nullable=True),
    sa.Column('cov_person', sa.Boolean(), nullable=True),
    sa.Column('cov_object', sa.String(length=10), nullable=True),
    sa.Column('cov_self', sa.String(length=10), nullable=True),
    sa.Column('cov_car', sa.String(length=10), nullable=True),
    sa.Column('cov_noncover', sa.String(length=10), nullable=True),
    sa.Column('spc_emergency', sa.String(length=10), nullable=True),
    sa.Column('spc_blackbox', sa.Boolean(), nullable=True),
    sa.Column('spc_mileage', sa.Boolean(), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exp_date', sa.Date(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('rst_company', sa.String(length=30), nullable=True),
    sa.Column('rst_date', sa.Date(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gladfc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('glad_id', sa.String(length=20), nullable=True),
    sa.Column('glad_name', sa.String(length=60), nullable=True),
    sa.Column('glad_brh', sa.String(length=100), nullable=True),
    sa.Column('tel_no', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('glad_id', sa.String(length=60), nullable=True),
    sa.Column('tel_no', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_glad_id'), 'employees', ['glad_id'], unique=True)
    op.create_index(op.f('ix_employees_tel_no'), 'employees', ['tel_no'], unique=False)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_index(op.f('ix_employees_tel_no'), table_name='employees')
    op.drop_index(op.f('ix_employees_glad_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('roles')
    op.drop_table('gladfc')
    op.drop_table('departments')
    op.drop_table('cars')
    # ### end Alembic commands ###
