"""empty message

Revision ID: 33bc683404bd
Revises: 1312d9703e28
Create Date: 2020-04-16 08:39:11.784676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33bc683404bd'
down_revision = '1312d9703e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('rst_company', sa.String(length=30), nullable=True))
    op.add_column('cars', sa.Column('rst_date', sa.Date(), nullable=True))
    op.add_column('cars', sa.Column('status', sa.String(length=10), nullable=True))
    op.add_column('cars', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'updated')
    op.drop_column('cars', 'status')
    op.drop_column('cars', 'rst_date')
    op.drop_column('cars', 'rst_company')
    # ### end Alembic commands ###
