"""empty message

Revision ID: 48887704fde3
Revises: 323b55118128
Create Date: 2020-04-23 15:41:08.475408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48887704fde3'
down_revision = '323b55118128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('지점', sa.String(length=30), nullable=True),
    sa.Column('직할지점', sa.String(length=30), nullable=True),
    sa.Column('팀', sa.String(length=30), nullable=True),
    sa.Column('수금사원번호', sa.String(length=20), nullable=True),
    sa.Column('수금사원명', sa.String(length=30), nullable=True),
    sa.Column('증권번호', sa.String(length=30), nullable=True),
    sa.Column('계약일자', sa.Date(), nullable=True),
    sa.Column('보험사', sa.String(length=30), nullable=True),
    sa.Column('계약종류', sa.String(length=20), nullable=True),
    sa.Column('상품종류', sa.String(length=20), nullable=True),
    sa.Column('초회보험료', sa.Integer(), nullable=True),
    sa.Column('계약상태', sa.String(length=10), nullable=True),
    sa.Column('납입회차', sa.SmallInteger(), nullable=True),
    sa.Column('납입방법', sa.String(length=10), nullable=True),
    sa.Column('최종상태변경일', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('증권번호')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    # ### end Alembic commands ###
