"""empty message

Revision ID: 5054bc398f52
Revises: 31dd379a52b4
Create Date: 2020-04-06 17:32:21.745223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5054bc398f52'
down_revision = '31dd379a52b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('cov_noncover', sa.Boolean(), nullable=True))
    op.drop_column('cars', 'con_noncover')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('con_noncover', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('cars', 'cov_noncover')
    # ### end Alembic commands ###
