"""empty message

Revision ID: 53c2260bbf85
Revises: 50bc755eed70
Create Date: 2020-05-13 08:35:42.126670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53c2260bbf85'
down_revision = '50bc755eed70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('rt_cause', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'rt_cause')
    op.create_table('contracts',
    sa.Column('지점', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('직할지점', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('팀', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('수금사원번호', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('수금사원명', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('증권번호', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('계약일자', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('보험사', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('계약종류', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('상품종류', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('초회보험료', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('계약상태', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('납입회차', mysql.INTEGER(display_width=2, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('납입방법', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('최종상태변경일', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('원수사성적', mysql.INTEGER(display_width=20, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('신글로벌성적', mysql.INTEGER(display_width=20, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('계약자', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('피보험자', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('최종납입년월', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('최종수금일', mysql.VARCHAR(length=10), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
