"""empty message

Revision ID: 75c94d9c76df
Revises: c496d4cae3bf
Create Date: 2020-04-07 14:50:30.542599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c94d9c76df'
down_revision = 'c496d4cae3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('cov_noncover', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'cov_noncover')
    # ### end Alembic commands ###
