"""empty message

Revision ID: b53faf491165
Revises: 53c2260bbf85
Create Date: 2020-06-18 16:45:04.616558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53faf491165'
down_revision = '53c2260bbf85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('상품명', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', '상품명')
    # ### end Alembic commands ###
