"""empty message

Revision ID: c3684d136fbe
Revises: 5054bc398f52
Create Date: 2020-04-07 13:58:49.258149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3684d136fbe'
down_revision = '5054bc398f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('cars', sa.Column('exp_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'exp_date')
    op.drop_column('cars', 'created')
    # ### end Alembic commands ###
