"""empty message

Revision ID: c496d4cae3bf
Revises: c3684d136fbe
Create Date: 2020-04-07 14:48:49.684183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c496d4cae3bf'
down_revision = 'c3684d136fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'cov_noncover')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('cov_noncover', mysql.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
