"""empty message

Revision ID: c8161e00e671
Revises: 48887704fde3
Create Date: 2020-04-24 15:45:35.324014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8161e00e671'
down_revision = '48887704fde3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('증권번호', table_name='contracts')
    op.drop_table('contracts')
    op.drop_index('ix_test_index', table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('index', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('지점', mysql.TEXT(), nullable=True),
    sa.Column('직할지점', mysql.TEXT(), nullable=True),
    sa.Column('팀', mysql.TEXT(), nullable=True),
    sa.Column('수금사원번호', mysql.TEXT(), nullable=True),
    sa.Column('수금사원명', mysql.TEXT(), nullable=True),
    sa.Column('증권번호', mysql.TEXT(), nullable=True),
    sa.Column('계약일자', mysql.TEXT(), nullable=True),
    sa.Column('보험사', mysql.TEXT(), nullable=True),
    sa.Column('계약종류', mysql.TEXT(), nullable=True),
    sa.Column('상품종류', mysql.TEXT(), nullable=True),
    sa.Column('초회보험료', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('계약상태', mysql.TEXT(), nullable=True),
    sa.Column('납입회차', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('납입주기(방법)', mysql.TEXT(), nullable=True),
    sa.Column('최종상태변경일', mysql.TEXT(), nullable=True),
    sa.Column('원수사성적', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('(신)글로벌성적', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('계약자', mysql.TEXT(), nullable=True),
    sa.Column('피보험자', mysql.TEXT(), nullable=True),
    sa.Column('최종납입년월', mysql.TEXT(), nullable=True),
    sa.Column('최종수금일', mysql.TEXT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_test_index', 'test', ['index'], unique=False)
    op.create_table('contracts',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('지점', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('직할지점', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('팀', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('수금사원번호', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('수금사원명', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('증권번호', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('계약일자', sa.DATE(), nullable=True),
    sa.Column('보험사', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('계약종류', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('상품종류', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('초회보험료', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('계약상태', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('납입회차', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('납입방법', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('최종상태변경일', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('증권번호', 'contracts', ['증권번호'], unique=True)
    # ### end Alembic commands ###
