"""empty message

Revision ID: f1999982dc1a
Revises: f106e3841905
Create Date: 2020-04-03 10:29:01.515026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1999982dc1a'
down_revision = 'f106e3841905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('filename', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'filename')
    # ### end Alembic commands ###
